apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: openshift-gitops-manage-quota-and-ranges
rules:
- apiGroups: [""]
  resources: ["resourcequotas", "limitranges"]
  verbs: ["*"]