apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-projects
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: 'openshift-gitops'
    server: {{ .Values.spec.destination.server }}
  source:
    path: argocd-projects/
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true