apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: project-memes-prod
bases:
- ../../base

# Patches are edits to make to a set of one or more targets
patches:
# This patch targets the Namespace resource and changes the
# value of metadata.name to "project-memes-prod"
- target:
    kind: Namespace
    name: for-replacement
  patch: |-
    - op: replace
      path: /metadata/name
      value: project-memes-prod
# This patch targets the resource quota. It doubles the available
# resources compared to the default values
- target:
    kind: ResourceQuota
    name: resource-quota-memory-cpu
  patch: |-
    - op: replace
      path: /spec/hard/cpu
      value: 1
    - op: replace
      path: /spec/hard/memory
      value: 1Gi